# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes_books', '0002_auto_20180322_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='notes',
        ),
    ]
